server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy /api/node to Node backend (if needed)
    # proxy_pass http://backend-node:5000;
}
