FROM node:20-alpine
WORKDIR /app

# Cài đặt các dependencies
COPY package*.json ./
RUN npm install

# Copy source code của Node.js
COPY index.js .
COPY services/ ./services/

EXPOSE 5000
CMD ["npm", "start"]
